constellations = {1: {'model_type': 'logreg-scikit',
                      'preprocess': True,
                      'robust_only': True,
                      'tol': 1e-4,
                      'C': 1.5,
                      'logreg_solver': 'lbfgs',
                      'max_iter': 100,
                      'svm_C': 1.0,
                      'svm_kernel': 'linear',
                      'svm_gamma': 'auto',
                      'svm_tol': 1e-3,
                      'svm_max_iter': -1,
                      'analyzer': 'word',
                      'ngram_range': (1, 1),
                      'max_df': 1.0,
                      'min_df': 1,
                      'max_features': 1.0,
                      'binary': False,
                      'norm': 'l2',
                      'use_idf': True,
                      'smooth_idf': True,
                      'sublinear_tf': True},

                  2: {'model_type': 'logreg-scikit',
                      'preprocess': True,
                      'robust_only': True,
                      'tol': 1e-4,
                      'C': 1.5,
                      'logreg_solver': 'lbfgs',
                      'max_iter': 100,
                      'svm_C': 1.0,
                      'svm_kernel': 'linear',
                      'svm_gamma': 'auto',
                      'svm_tol': 1e-3,
                      'svm_max_iter': -1,
                      'analyzer': 'word',
                      'ngram_range': (1, 1),
                      'max_df': 1.0,
                      'min_df': 1,
                      'max_features': 1.0,
                      'binary': False,
                      'norm': 'l2',
                      'use_idf': True,
                      'smooth_idf': True,
                      'sublinear_tf': False},

                  3: {'model_type': 'logreg-scikit',
                      'preprocess': True,
                      'robust_only': True,
                      'tol': 1e-4,
                      'C': 1.5,
                      'logreg_solver': 'lbfgs',
                      'max_iter': 100,
                      'svm_C': 1.0,
                      'svm_kernel': 'linear',
                      'svm_gamma': 'auto',
                      'svm_tol': 1e-3,
                      'svm_max_iter': -1,
                      'analyzer': 'word',
                      'ngram_range': (1, 1),
                      'max_df': 1.0,
                      'min_df': 1,
                      'max_features': 1.0,
                      'binary': False,
                      'norm': 'l2',
                      'use_idf': True,
                      'smooth_idf': False,
                      'sublinear_tf': True},

                  4: {'model_type': 'logreg-scikit',
                      'preprocess': True,
                      'robust_only': True,
                      'tol': 1e-4,
                      'C': 1.5,
                      'logreg_solver': 'lbfgs',
                      'max_iter': 100,
                      'svm_C': 1.0,
                      'svm_kernel': 'linear',
                      'svm_gamma': 'auto',
                      'svm_tol': 1e-3,
                      'svm_max_iter': -1,
                      'analyzer': 'word',
                      'ngram_range': (1, 1),
                      'max_df': 1.0,
                      'min_df': 1,
                      'max_features': 1.0,
                      'binary': False,
                      'norm': 'l2',
                      'use_idf': False,
                      'smooth_idf': True,
                      'sublinear_tf': True},

                  5: {'model_type': 'logreg-scikit',
                      'preprocess': True,
                      'robust_only': True,
                      'tol': 1e-4,
                      'C': 1.5,
                      'logreg_solver': 'lbfgs',
                      'max_iter': 100,
                      'svm_C': 1.0,
                      'svm_kernel': 'linear',
                      'svm_gamma': 'auto',
                      'svm_tol': 1e-3,
                      'svm_max_iter': -1,
                      'analyzer': 'word',
                      'ngram_range': (1, 1),
                      'max_df': 1.0,
                      'min_df': 1,
                      'max_features': 1.0,
                      'binary': False,
                      'norm': 'l1',
                      'use_idf': True,
                      'smooth_idf': True,
                      'sublinear_tf': True},

                  6: {'model_type': 'logreg-scikit',
                      'preprocess': True,
                      'robust_only': True,
                      'tol': 1e-4,
                      'C': 1.5,
                      'logreg_solver': 'lbfgs',
                      'max_iter': 100,
                      'svm_C': 1.0,
                      'svm_kernel': 'linear',
                      'svm_gamma': 'auto',
                      'svm_tol': 1e-3,
                      'svm_max_iter': -1,
                      'analyzer': 'word',
                      'ngram_range': (1, 1),
                      'max_df': 1.0,
                      'min_df': 1,
                      'max_features': 1.0,
                      'binary': True,
                      'norm': 'l2',
                      'use_idf': True,
                      'smooth_idf': True,
                      'sublinear_tf': True},

                  7: {'model_type': 'logreg-scikit',
                      'preprocess': True,
                      'robust_only': False,
                      'tol': 1e-4,
                      'C': 1.5,
                      'logreg_solver': 'lbfgs',
                      'max_iter': 100,
                      'svm_C': 1.0,
                      'svm_kernel': 'linear',
                      'svm_gamma': 'auto',
                      'svm_tol': 1e-3,
                      'svm_max_iter': -1,
                      'analyzer': 'word',
                      'ngram_range': (1, 1),
                      'max_df': 1.0,
                      'min_df': 1,
                      'max_features': 1.0,
                      'binary': False,
                      'norm': 'l2',
                      'use_idf': True,
                      'smooth_idf': True,
                      'sublinear_tf': True},

                  8: {'model_type': 'logreg-scikit',
                      'preprocess': False,
                      'robust_only': True,
                      'tol': 1e-4,
                      'C': 1.5,
                      'logreg_solver': 'lbfgs',
                      'max_iter': 100,
                      'svm_C': 1.0,
                      'svm_kernel': 'linear',
                      'svm_gamma': 'auto',
                      'svm_tol': 1e-3,
                      'svm_max_iter': -1,
                      'analyzer': 'word',
                      'ngram_range': (1, 1),
                      'max_df': 1.0,
                      'min_df': 1,
                      'max_features': 1.0,
                      'binary': False,
                      'norm': 'l2',
                      'use_idf': True,
                      'smooth_idf': True,
                      'sublinear_tf': True},

                  9: {'model_type': 'svm-scikit',
                      'preprocess': True,
                      'robust_only': True,
                      'tol': 1e-4,
                      'C': 1.5,
                      'logreg_solver': 'lbfgs',
                      'max_iter': 100,
                      'svm_C': 1.0,
                      'svm_kernel': 'linear',
                      'svm_gamma': 'auto',
                      'svm_tol': 1e-3,
                      'svm_max_iter': -1,
                      'analyzer': 'word',
                      'ngram_range': (1, 1),
                      'max_df': 1.0,
                      'min_df': 1,
                      'max_features': 1.0,
                      'binary': False,
                      'norm': 'l2',
                      'use_idf': True,
                      'smooth_idf': True,
                      'sublinear_tf': True},

                  10: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'char',
                       'ngram_range': (2, 2),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  11: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'char',
                       'ngram_range': (3, 3),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  12: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'char',
                       'ngram_range': (4, 4),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  13: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'char',
                       'ngram_range': (5, 5),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  14: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 0.1,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  15: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 0.05,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  16: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 0.025,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  17: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 0.0125,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  18: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 0.00625,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  19: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': False,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': False},

                  20: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': False,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': False,
                       'sublinear_tf': True},

                  21: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': False,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': False,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  22: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': False,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l1',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  23: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': False,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': True,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  24: {'model_type': 'logreg-scikit',
                       'preprocess': False,
                       'robust_only': False,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  25: {'model_type': 'logreg-scikit',
                       'preprocess': False,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': False},

                  26: {'model_type': 'logreg-scikit',
                       'preprocess': False,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': False,
                       'sublinear_tf': True},

                  27: {'model_type': 'logreg-scikit',
                       'preprocess': False,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': False,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  28: {'model_type': 'logreg-scikit',
                       'preprocess': False,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l1',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  29: {'model_type': 'logreg-scikit',
                       'preprocess': False,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': True,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  30: {'model_type': 'svm-scikit',
                       'preprocess': False,
                       'robust_only': False,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  31: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': True,
                       'norm': 'l2',
                       'use_idf': False,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  32: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': True,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': False,
                       'sublinear_tf': True},

                  33: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': False,
                       'sublinear_tf': False},

                  34: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 0.025,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': False},

                  35: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 25,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  36: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 10,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  37: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 5,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  38: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 2,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  39: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  40: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 0.01,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  41: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 0.1,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  42: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  43: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 10,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  44: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 25,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 1.0,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  45: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 0.1,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  46: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 0.05,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  47: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 0.025,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  48: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 0.0125,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  49: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 0.00625,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True},

                  50: {'model_type': 'logreg-scikit',
                       'preprocess': True,
                       'robust_only': True,
                       'tol': 1e-4,
                       'C': 1.5,
                       'logreg_solver': 'lbfgs',
                       'max_iter': 100,
                       'svm_C': 1.0,
                       'svm_kernel': 'linear',
                       'svm_gamma': 'auto',
                       'svm_tol': 1e-3,
                       'svm_max_iter': -1,
                       'analyzer': 'word',
                       'ngram_range': (1, 1),
                       'max_df': 1.0,
                       'min_df': 1,
                       'max_features': 0.003125,
                       'binary': False,
                       'norm': 'l2',
                       'use_idf': True,
                       'smooth_idf': True,
                       'sublinear_tf': True}}
